# Generated by Django 3.2 on 2022-07-10 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(max_length=32, verbose_name='应用')),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(max_length=32, verbose_name='接口名称')),
                ('service_id', models.CharField(max_length=16, verbose_name='ESB ID')),
                ('create_time', models.CharField(max_length=128, verbose_name='创建时间')),
                ('interface_method', models.SmallIntegerField(choices=[(1, 'POST'), (2, 'GET')], verbose_name='接口方式')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QQTest.application')),
            ],
        ),
    ]
